### PR TITLE
Séance du 19/05/2021

### PR DESCRIPTION
**Pull request by Manud237**

### CODE REVIEW

**Comment by massimotisi** [comment]
You are changing files outside of your java package. You can see the files that you are changing in the "Files changed" tab of your pull request on the github website. This list must contain only files in your package.

You can replace them with the version from the main repository. To do that, right click on these files or folders -> Replace with -> Branch, Tag or Reference -> Remote tracking -> select the main repository -> Replace. If the files or folders do not exist in the main repository, you can simply delete them. Then commit and push to your repository.

**Comment by Manud237** [comment]
I replaced the files.

**Comment by massimotisi** [comment]
You did not remove the files outside of your package. Again, please check https://github.com/CACAO2021/CACAO2021/pull/115/files

**Comment by Manud237** [comment]
I followed the instructions to replace files but nothing happens. And I don't know if I have the right to delete them.

**Comment by massimotisi** [comment]
Please delete `junit833569376840363297.properties` and `junitvmwatcher12634451166249240371.properties` and push.

**Pull request merged**
