### PR TITLE
21/04/2021

### PR DESCRIPTION
**Pull request by lenalf13**

### CODE REVIEW

**Comment by massimotisi** [comment]
Not accepting because you are changing `src/abstraction/eq8Romu/produits/Chocolat.java`

**Comment by massimotisi** [comment]
See here https://github.com/CACAO2021/CACAO2021/wiki#changes-outside-of-your-package

**Comment by massimotisi** [comment]
Your code has a compilation error (red mark in Eclipse). You can read the error message by going in the tab "Checks" of your pull request and opening the log "Java CI / build". Please fix it and commit+push again.

**Comment by massimotisi** [comment]
Not accepting because you are changing `src/abstraction/eq8Romu/produits/Chocolat.java`
See here https://github.com/CACAO2021/CACAO2021/wiki#changes-outside-of-your-package

**Comment by massimotisi** [comment]
@CACAO2021/eq5transformateur3 please solve the problem otherwise your pull request will not be merged

**Comment by Manud237** [comment]
Je crois que c'est bon.

**Pull request merged**
