### PR TITLE
avancée 7 avril

### PR DESCRIPTION
**Pull request by Charlottederom**

### CODE REVIEW

**Comment by massimotisi** [comment]
Not accepting because of NullPointerException. 

(you can see the full exception if you click on Details of the failed check)

**Comment by massimotisi** [comment]
See also https://github.com/CACAO2021/CACAO2021/wiki#execution-error

**Comment by massimotisi** [comment]
@CACAO2021/eq5transformateur3 any news?

**Comment by Manud237** [comment]
Je pense que là c'est bon.

**Pull request merged**
